"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0sw$+79d4*d=+kqrya5a))k!ev979@x+fv%k-bqttrp5j3m6(s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'standard_app.apps.StandardAppConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import pymysql
pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mydate',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

# CORS Config
CORS_ALLOW_ALL_ORIGINS = True

# DRF Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Custom User Model
AUTH_USER_MODEL = 'standard_app.CustomUser'

USE_I18N = True

USE_TZ = True

# Celery & Redis Configuration
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Django 缓存（复用已有 Redis，用 db 2 避免与 Celery 冲突）
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/2',
    }
}

# 标准源文件共享盘自适应配置（Windows 开发环境 vs Linux 部署环境）
import platform
if platform.system() == 'Windows':
    SHARED_DISK_DIR = r'Z:\磁盘阵列\标准文件处理'
else:
    # Linux 部署环境（见 升级部署文档.md 中约定的大文件共享挂载目录）
    SHARED_DISK_DIR = r'/mnt/std_bk/磁盘阵列/标准文件下载/'
# 标准类别 -> 子文件夹映射（可按实际目录名在下方增改）
SHARED_DISK_TYPE_FOLDERS = {
    'GB': ['word的国标', '待处理'],
    'DB': ['word的地标'],
    'HB': ['word的行标'],
    'TB': ['word的行标', '食品安全标准word版'],
    'ISO': ['待处理', 'word的国标'],
    'IEC': ['待处理', 'word的国标'],
    'IEEE': ['待处理', 'word的国标'],
}
# 是否在分类目录未命中时递归整个根目录（慢，仅调试时开启）
SHARED_DISK_DEEP_SEARCH = False

# Elasticsearch（不可用时会熔断并走 MySQL；未部署 ES 时可设 USE_ELASTICSEARCH=false）
USE_ELASTICSEARCH = os.getenv('USE_ELASTICSEARCH', 'false').lower() in ('1', 'true', 'yes')
ES_HOST = os.getenv('ES_HOST', 'http://127.0.0.1:9200')
ES_INDEX = os.getenv('ES_INDEX', 'standards')
ES_REQUEST_TIMEOUT = float(os.getenv('ES_REQUEST_TIMEOUT', '2'))
ES_CIRCUIT_COOLDOWN = int(os.getenv('ES_CIRCUIT_COOLDOWN', '120'))
ES_CIRCUIT_MAX_FAILURES = int(os.getenv('ES_CIRCUIT_MAX_FAILURES', '2'))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
