# Generated by Django 4.2.30 on 2026-05-08 07:42

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDict',
            fields=[
                ('area_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('province_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('county_name', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QbMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enterprise_bz_id', models.CharField(blank=True, max_length=255, null=True)),
                ('refer_bz_id', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'qb_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Std4754Tree',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'std_4754_tree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Std4757Search',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_code', models.CharField(blank=True, max_length=50, null=True)),
                ('target_name', models.CharField(blank=True, max_length=255, null=True)),
                ('level_1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('level_2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('level_3_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'std_4757_search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdBase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_id', models.CharField(blank=True, max_length=255, null=True)),
                ('std_type', models.CharField(blank=True, max_length=50, null=True)),
                ('std_type_no', models.CharField(blank=True, max_length=50, null=True)),
                ('std_chinesename', models.CharField(blank=True, max_length=1000, null=True)),
                ('std_englishname', models.CharField(blank=True, max_length=1000, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('implement_date', models.DateField(blank=True, null=True)),
                ('abolish_date', models.DateField(blank=True, null=True)),
                ('std_status', models.CharField(blank=True, max_length=50, null=True)),
                ('ex_state', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'std_base',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdCcsDict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ccs_code', models.CharField(blank=True, max_length=50, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=50, null=True)),
                ('name_level_1', models.CharField(blank=True, max_length=255, null=True)),
                ('name_level_2', models.CharField(blank=True, max_length=255, null=True)),
                ('name_level_3', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'std_ccs_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdDbDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ccs', models.CharField(blank=True, max_length=255, null=True)),
                ('ics', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('std_indu_type', models.CharField(blank=True, max_length=255, null=True)),
                ('record_no', models.CharField(blank=True, max_length=255, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('rev_type', models.CharField(blank=True, max_length=255, null=True)),
                ('tech_committee', models.CharField(blank=True, max_length=255, null=True)),
                ('approve_dept', models.CharField(blank=True, max_length=255, null=True)),
                ('suggest_dept', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'std_db_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdExtendH',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_type', models.CharField(blank=True, max_length=50, null=True)),
                ('draft_unit', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'std_extend_h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdExtendS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_type', models.CharField(blank=True, max_length=50, null=True)),
                ('draft_unit', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'std_extend_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdGbDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ccs', models.CharField(blank=True, max_length=255, null=True)),
                ('ics', models.CharField(blank=True, max_length=255, null=True)),
                ('drafter', models.TextField(blank=True, null=True)),
                ('report_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_report_unit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'std_gb_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdHbDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ccs', models.CharField(blank=True, max_length=255, null=True)),
                ('ics', models.CharField(blank=True, max_length=255, null=True)),
                ('drafter', models.TextField(blank=True, null=True)),
                ('report_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_report_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('std_indu_type', models.CharField(blank=True, max_length=255, null=True)),
                ('record_no', models.CharField(blank=True, max_length=255, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('rev_type', models.CharField(blank=True, max_length=255, null=True)),
                ('tech_committee', models.CharField(blank=True, max_length=255, null=True)),
                ('approve_dept', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'std_hb_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdIcsDict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ics_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ics_code_u', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_level_1', models.CharField(blank=True, max_length=255, null=True)),
                ('name_level_2', models.CharField(blank=True, max_length=255, null=True)),
                ('name_level_3', models.CharField(blank=True, max_length=255, null=True)),
                ('extend_category', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('extend_notes', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'std_ics_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdIndex',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index_name', models.CharField(blank=True, max_length=255, null=True)),
                ('index_type', models.IntegerField(blank=True, null=True)),
                ('index_context', models.JSONField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'std_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdPedChain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ped_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ped_chain', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'std_ped_chain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdPedigree',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_id_latest', models.CharField(blank=True, max_length=255, null=True)),
                ('ped_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'std_pedigree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdReplace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('replace_id', models.IntegerField(blank=True, null=True)),
                ('replace_std_name', models.CharField(blank=True, max_length=255, null=True)),
                ('replace_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'std_replace',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdStatistical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('refer_num', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'std_statistical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdTbDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ccs', models.CharField(blank=True, max_length=255, null=True)),
                ('ics', models.CharField(blank=True, max_length=255, null=True)),
                ('gbc', models.CharField(blank=True, max_length=255, null=True)),
                ('drafter', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('main_tech_cont', models.TextField(blank=True, null=True)),
                ('is_patent', models.IntegerField(blank=True, null=True)),
                ('std_text', models.IntegerField(blank=True, null=True)),
                ('tb_asso', models.CharField(blank=True, max_length=255, null=True)),
                ('regi_no', models.CharField(blank=True, max_length=255, null=True)),
                ('issu_auth', models.CharField(blank=True, max_length=255, null=True)),
                ('buss_scope', models.TextField(blank=True, null=True)),
                ('charge_person', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'std_tb_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StdUnitRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_type', models.IntegerField(blank=True, null=True)),
                ('rank_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'std_unit_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitDict',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('area_code', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'unit_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewStdFull',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('std_id', models.CharField(blank=True, max_length=255, null=True)),
                ('std_type', models.CharField(blank=True, max_length=50, null=True)),
                ('std_type_no', models.CharField(blank=True, max_length=50, null=True)),
                ('std_chinesename', models.CharField(blank=True, max_length=1000, null=True)),
                ('std_englishname', models.CharField(blank=True, max_length=1000, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('implement_date', models.DateField(blank=True, null=True)),
                ('ex_state', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('ccs', models.CharField(blank=True, max_length=255, null=True)),
                ('ics', models.CharField(blank=True, max_length=255, null=True)),
                ('drafter', models.TextField(blank=True, null=True)),
                ('report_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_report_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('std_indu_type', models.CharField(blank=True, max_length=255, null=True)),
                ('record_no', models.CharField(blank=True, max_length=255, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('rev_type', models.CharField(blank=True, max_length=255, null=True)),
                ('tech_committee', models.CharField(blank=True, max_length=255, null=True)),
                ('approve_dept', models.CharField(blank=True, max_length=255, null=True)),
                ('gbc', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('main_tech_cont', models.TextField(blank=True, null=True)),
                ('is_patent', models.IntegerField(blank=True, null=True)),
                ('std_text', models.IntegerField(blank=True, null=True)),
                ('tb_asso', models.CharField(blank=True, max_length=255, null=True)),
                ('regi_no', models.CharField(blank=True, max_length=255, null=True)),
                ('issu_auth', models.CharField(blank=True, max_length=255, null=True)),
                ('buss_scope', models.TextField(blank=True, null=True)),
                ('charge_person', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'view_std_full',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('gmt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
